// @ts-nocheck
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { appApi } from '@/lib/appApi';
import { useCompany } from '@/lib/CompanyContext';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const peso = value => `₱${Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function Agency() {
  const { activeCompanyId, activeCompany } = useCompany();
  const [periodId, setPeriodId] = useState('latest');
  const [search, setSearch] = useState('');
  const [method, setMethod] = useState('all');
  const periodsQuery = useQuery({ queryKey: ['payrollPeriods', activeCompanyId, 'agency'], queryFn: () => appApi.entities.PayrollPeriod.filter({ company_profile_id: activeCompanyId }, '-start_date', 100), enabled: !!activeCompanyId });
  const summaryQuery = useQuery({ queryKey: ['agencySummary', activeCompanyId, periodId], queryFn: () => appApi.functions.invoke('getAgencySummary', { company_profile_id: activeCompanyId, payroll_period_id: periodId === 'latest' ? periodsQuery.data?.[0]?.id : periodId }), enabled: !!activeCompanyId && periodsQuery.isSuccess });
  const summary = summaryQuery.data;
  const filtered = useMemo(() => (summary?.employees || []).filter(employee => `${employee.first_name || ''} ${employee.employee_id || ''} ${employee.department || ''}`.toLowerCase().includes(search.toLowerCase()) && (method === 'all' || employee.payrollMethod === method)), [method, search, summary]);
  if (!activeCompany?.uses_employee_agency) return <div className="p-6"><Card><CardContent className="p-8 text-center"><p className="font-semibold">Agency support is not enabled</p><p className="text-sm text-muted-foreground">Enable it from Company Profile.</p></CardContent></Card></div>;
  return <div className="p-6 max-w-6xl mx-auto space-y-5"><div><h1 className="text-2xl font-bold">Agency</h1><p className="text-sm text-muted-foreground">Agency fee computation by payroll cutoff</p></div><Select value={periodId} onValueChange={setPeriodId}><SelectTrigger className="max-w-sm"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="latest">Latest Payroll Period</SelectItem>{(periodsQuery.data || []).map(period => <SelectItem key={period.id} value={String(period.id)}>{period.period_name}</SelectItem>)}</SelectContent></Select>{summaryQuery.isLoading ? <p>Loading…</p> : <><div className="grid sm:grid-cols-3 gap-3"><Card><CardContent className="p-5"><p className="text-2xl font-bold">{summary?.employeeCount || 0}</p><p className="text-xs text-muted-foreground">Agency Employees</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-2xl font-bold">{peso(summary?.feePerEmployee)}</p><p className="text-xs text-muted-foreground">Fee per Employee · {(summary?.frequency || '').replace('_', ' ')}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-2xl font-bold text-primary">{peso(summary?.totalAgencyFee)}</p><p className="text-xs text-muted-foreground">Total Agency Fee</p></CardContent></Card></div><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search agency employee..." value={search} onChange={e => setSearch(e.target.value)}/></div><Select value={method} onValueChange={setMethod}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Methods</SelectItem><SelectItem value="ATM">ATM</SelectItem><SelectItem value="NON_ATM">Non-ATM</SelectItem><SelectItem value="UNASSIGNED">Unassigned</SelectItem></SelectContent></Select></div><Card className="overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Employee</th><th className="p-3 text-left">Employee No.</th><th className="p-3 text-left">Department</th><th className="p-3 text-left">Payroll Method</th><th className="p-3 text-right">Agency Fee</th></tr></thead><tbody>{filtered.map(employee => <tr key={employee.id} className="border-t"><td className="p-3 font-medium">{employee.first_name}</td><td className="p-3">{employee.employee_id}</td><td className="p-3">{employee.department || '—'}</td><td className="p-3">{employee.payrollMethod.replace('_', '-')}</td><td className="p-3 text-right">{peso(employee.agency_fee_amount ?? summary.feePerEmployee)}</td></tr>)}</tbody><tfoot><tr className="border-t font-semibold"><td className="p-3" colSpan={4}>Total · {filtered.length} employees</td><td className="p-3 text-right">{peso(filtered.reduce((sum, employee) => sum + Number(employee.agency_fee_amount ?? summary.feePerEmployee), 0))}</td></tr></tfoot></table></Card></>}</div>;
}
